// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Memo } from "./memo_service_pb";
import { file_api_v1_memo_service } from "./memo_service_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIkkKEVRyYW5zY3JpYmVSZXF1ZXN0EjQKBWF1ZGlvGAEgASgLMiAubWVtb3MuYXBpLnYxLlRyYW5zY3JpcHRpb25BdWRpb0ID4EECIncKElRyYW5zY3JpcHRpb25BdWRpbxIWCgdjb250ZW50GAEgASgMQgPgQQRIABINCgN1cmkYAiABKAlIABIVCghmaWxlbmFtZRgDIAEoCUID4EEBEhkKDGNvbnRlbnRfdHlwZRgEIAEoCUID4EEBQggKBnNvdXJjZSIiChJUcmFuc2NyaWJlUmVzcG9uc2USDAoEdGV4dBgBIAEoCSI8ChJTZWFyY2hNZW1vc1JlcXVlc3QSEgoFcXVlcnkYASABKAlCA+BBAhISCgVsaW1pdBgCIAEoBUID4EEBIosBChNTZWFyY2hNZW1vc1Jlc3BvbnNlEjkKB3Jlc3VsdHMYASADKAsyKC5tZW1vcy5hcGkudjEuU2VhcmNoTWVtb3NSZXNwb25zZS5SZXN1bHQaOQoGUmVzdWx0EiAKBG1lbW8YASABKAsyEi5tZW1vcy5hcGkudjEuTWVtbxINCgVzY29yZRgCIAEoAjKFAgoJQUlTZXJ2aWNlEnkKClRyYW5zY3JpYmUSHy5tZW1vcy5hcGkudjEuVHJhbnNjcmliZVJlcXVlc3QaIC5tZW1vcy5hcGkudjEuVHJhbnNjcmliZVJlc3BvbnNlIijaQQVhdWRpb4LT5JMCGjoBKiIVL2FwaS92MS9haTp0cmFuc2NyaWJlEn0KC1NlYXJjaE1lbW9zEiAubWVtb3MuYXBpLnYxLlNlYXJjaE1lbW9zUmVxdWVzdBohLm1lbW9zLmFwaS52MS5TZWFyY2hNZW1vc1Jlc3BvbnNlIinaQQVxdWVyeYLT5JMCGzoBKiIWL2FwaS92MS9haTpzZWFyY2hNZW1vc0KmAQoQY29tLm1lbW9zLmFwaS52MUIOQWlTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_api_v1_memo_service, file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.TranscribeRequest
 */
export type TranscribeRequest = Message<"memos.api.v1.TranscribeRequest"> & {
  /**
   * Required. Audio input.
   *
   * @generated from field: memos.api.v1.TranscriptionAudio audio = 1;
   */
  audio?: TranscriptionAudio | undefined;
};

/**
 * Describes the message memos.api.v1.TranscribeRequest.
 * Use `create(TranscribeRequestSchema)` to create a new message.
 */
export const TranscribeRequestSchema: GenMessage<TranscribeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.TranscriptionAudio
 */
export type TranscriptionAudio = Message<"memos.api.v1.TranscriptionAudio"> & {
  /**
   * @generated from oneof memos.api.v1.TranscriptionAudio.source
   */
  source: {
    /**
     * Inline audio bytes.
     *
     * @generated from field: bytes content = 1;
     */
    value: Uint8Array;
    case: "content";
  } | {
    /**
     * URI for audio content. Reserved for future use.
     *
     * @generated from field: string uri = 2;
     */
    value: string;
    case: "uri";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. The uploaded filename.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Optional. The MIME type of the input audio.
   *
   * @generated from field: string content_type = 4;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.TranscriptionAudio.
 * Use `create(TranscriptionAudioSchema)` to create a new message.
 */
export const TranscriptionAudioSchema: GenMessage<TranscriptionAudio> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.TranscribeResponse
 */
export type TranscribeResponse = Message<"memos.api.v1.TranscribeResponse"> & {
  /**
   * The transcribed text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.TranscribeResponse.
 * Use `create(TranscribeResponseSchema)` to create a new message.
 */
export const TranscribeResponseSchema: GenMessage<TranscribeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from message memos.api.v1.SearchMemosRequest
 */
export type SearchMemosRequest = Message<"memos.api.v1.SearchMemosRequest"> & {
  /**
   * Required. The natural-language search query.
   *
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * Optional. Maximum results to return. Defaults to 20, capped at 50.
   *
   * @generated from field: int32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message memos.api.v1.SearchMemosRequest.
 * Use `create(SearchMemosRequestSchema)` to create a new message.
 */
export const SearchMemosRequestSchema: GenMessage<SearchMemosRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 3);

/**
 * @generated from message memos.api.v1.SearchMemosResponse
 */
export type SearchMemosResponse = Message<"memos.api.v1.SearchMemosResponse"> & {
  /**
   * Results ordered by descending score.
   *
   * @generated from field: repeated memos.api.v1.SearchMemosResponse.Result results = 1;
   */
  results: SearchMemosResponse_Result[];
};

/**
 * Describes the message memos.api.v1.SearchMemosResponse.
 * Use `create(SearchMemosResponseSchema)` to create a new message.
 */
export const SearchMemosResponseSchema: GenMessage<SearchMemosResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4);

/**
 * @generated from message memos.api.v1.SearchMemosResponse.Result
 */
export type SearchMemosResponse_Result = Message<"memos.api.v1.SearchMemosResponse.Result"> & {
  /**
   * The matched memo.
   *
   * @generated from field: memos.api.v1.Memo memo = 1;
   */
  memo?: Memo | undefined;

  /**
   * Cosine similarity of the memo to the query, higher is closer.
   *
   * @generated from field: float score = 2;
   */
  score: number;
};

/**
 * Describes the message memos.api.v1.SearchMemosResponse.Result.
 * Use `create(SearchMemosResponse_ResultSchema)` to create a new message.
 */
export const SearchMemosResponse_ResultSchema: GenMessage<SearchMemosResponse_Result> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4, 0);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * Transcribe transcribes an audio file using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Transcribe
   */
  transcribe: {
    methodKind: "unary";
    input: typeof TranscribeRequestSchema;
    output: typeof TranscribeResponseSchema;
  },
  /**
   * SearchMemos ranks the calling user's own memos by semantic similarity to
   * the query. Results never include another user's memos.
   *
   * @generated from rpc memos.api.v1.AIService.SearchMemos
   */
  searchMemos: {
    methodKind: "unary";
    input: typeof SearchMemosRequestSchema;
    output: typeof SearchMemosResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

